(cl:in-package svg_ros-srv)
(cl:export '(SUCCESS-VAL
          SUCCESS
          ORIGIN_X-VAL
          ORIGIN_X
          ORIGIN_Y-VAL
          ORIGIN_Y
          ORIGIN_ANGROB-VAL
          ORIGIN_ANGROB
          DEST_X-VAL
          DEST_X
          DEST_Y-VAL
          DEST_Y
          SENSORBOOL-VAL
          SENSORBOOL
          NUM_SENSORSINT-VAL
          NUM_SENSORSINT
          ANGLE_SENSOR_ORIG-VAL
          ANGLE_SENSOR_ORIG
          RANGE_ANGLEROB-VAL
          RANGE_ANGLEROB
          RADIUSROB-VAL
          RADIUSROB
          ADVANCE-VAL
          ADVANCE
          MAX_ANGLE-VAL
          MAX_ANGLE
          NUM_STEPS-VAL
          NUM_STEPS
          SELECT-VAL
          SELECT
          LARGEST_SENSOR-VAL
          LARGEST_SENSOR
          PATHNAME-VAL
          PATHNAME
          FILENAME-VAL
          FILENAME
          FLGGUI-VAL
          FLGGUI
          FLG_NOISE-VAL
          FLG_NOISE
          FLG_REAL_ENVIRONMENT-VAL
          FLG_REAL_ENVIRONMENT
))