// Generated by gencpp from file svg_ros/InputsSrv.msg
// DO NOT EDIT!


#ifndef SVG_ROS_MESSAGE_INPUTSSRV_H
#define SVG_ROS_MESSAGE_INPUTSSRV_H

#include <ros/service_traits.h>


#include <svg_ros/InputsSrvRequest.h>
#include <svg_ros/InputsSrvResponse.h>


namespace svg_ros
{

struct InputsSrv
{

typedef InputsSrvRequest Request;
typedef InputsSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct InputsSrv
} // namespace svg_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::svg_ros::InputsSrv > {
  static const char* value()
  {
    return "f39e8e9b737ca0cd747aac4db3741413";
  }

  static const char* value(const ::svg_ros::InputsSrv&) { return value(); }
};

template<>
struct DataType< ::svg_ros::InputsSrv > {
  static const char* value()
  {
    return "svg_ros/InputsSrv";
  }

  static const char* value(const ::svg_ros::InputsSrv&) { return value(); }
};


// service_traits::MD5Sum< ::svg_ros::InputsSrvRequest> should match 
// service_traits::MD5Sum< ::svg_ros::InputsSrv > 
template<>
struct MD5Sum< ::svg_ros::InputsSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::svg_ros::InputsSrv >::value();
  }
  static const char* value(const ::svg_ros::InputsSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::svg_ros::InputsSrvRequest> should match 
// service_traits::DataType< ::svg_ros::InputsSrv > 
template<>
struct DataType< ::svg_ros::InputsSrvRequest>
{
  static const char* value()
  {
    return DataType< ::svg_ros::InputsSrv >::value();
  }
  static const char* value(const ::svg_ros::InputsSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::svg_ros::InputsSrvResponse> should match 
// service_traits::MD5Sum< ::svg_ros::InputsSrv > 
template<>
struct MD5Sum< ::svg_ros::InputsSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::svg_ros::InputsSrv >::value();
  }
  static const char* value(const ::svg_ros::InputsSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::svg_ros::InputsSrvResponse> should match 
// service_traits::DataType< ::svg_ros::InputsSrv > 
template<>
struct DataType< ::svg_ros::InputsSrvResponse>
{
  static const char* value()
  {
    return DataType< ::svg_ros::InputsSrv >::value();
  }
  static const char* value(const ::svg_ros::InputsSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SVG_ROS_MESSAGE_INPUTSSRV_H
