// Generated by gencpp from file svg_ros/MVPlannerSrvRequest.msg
// DO NOT EDIT!


#ifndef SVG_ROS_MESSAGE_MVPLANNERSRVREQUEST_H
#define SVG_ROS_MESSAGE_MVPLANNERSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace svg_ros
{
template <class ContainerAllocator>
struct MVPlannerSrvRequest_
{
  typedef MVPlannerSrvRequest_<ContainerAllocator> Type;

  MVPlannerSrvRequest_()
    : answer()  {
    }
  MVPlannerSrvRequest_(const ContainerAllocator& _alloc)
    : answer(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _answer_type;
  _answer_type answer;




  typedef boost::shared_ptr< ::svg_ros::MVPlannerSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::svg_ros::MVPlannerSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MVPlannerSrvRequest_

typedef ::svg_ros::MVPlannerSrvRequest_<std::allocator<void> > MVPlannerSrvRequest;

typedef boost::shared_ptr< ::svg_ros::MVPlannerSrvRequest > MVPlannerSrvRequestPtr;
typedef boost::shared_ptr< ::svg_ros::MVPlannerSrvRequest const> MVPlannerSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::svg_ros::MVPlannerSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::svg_ros::MVPlannerSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace svg_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::svg_ros::MVPlannerSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::svg_ros::MVPlannerSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::svg_ros::MVPlannerSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::svg_ros::MVPlannerSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::svg_ros::MVPlannerSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::svg_ros::MVPlannerSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::svg_ros::MVPlannerSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d7e708f879c94bb931716d8f4f130f30";
  }

  static const char* value(const ::svg_ros::MVPlannerSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd7e708f879c94bb9ULL;
  static const uint64_t static_value2 = 0x31716d8f4f130f30ULL;
};

template<class ContainerAllocator>
struct DataType< ::svg_ros::MVPlannerSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "svg_ros/MVPlannerSrvRequest";
  }

  static const char* value(const ::svg_ros::MVPlannerSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::svg_ros::MVPlannerSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string answer\n\
";
  }

  static const char* value(const ::svg_ros::MVPlannerSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::svg_ros::MVPlannerSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.answer);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MVPlannerSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::svg_ros::MVPlannerSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::svg_ros::MVPlannerSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "answer: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.answer);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SVG_ROS_MESSAGE_MVPLANNERSRVREQUEST_H
