// Generated by gencpp from file svg_ros/ReadySrv.msg
// DO NOT EDIT!


#ifndef SVG_ROS_MESSAGE_READYSRV_H
#define SVG_ROS_MESSAGE_READYSRV_H

#include <ros/service_traits.h>


#include <svg_ros/ReadySrvRequest.h>
#include <svg_ros/ReadySrvResponse.h>


namespace svg_ros
{

struct ReadySrv
{

typedef ReadySrvRequest Request;
typedef ReadySrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReadySrv
} // namespace svg_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::svg_ros::ReadySrv > {
  static const char* value()
  {
    return "481bf4557884a8ae5f3651bd90c8f18f";
  }

  static const char* value(const ::svg_ros::ReadySrv&) { return value(); }
};

template<>
struct DataType< ::svg_ros::ReadySrv > {
  static const char* value()
  {
    return "svg_ros/ReadySrv";
  }

  static const char* value(const ::svg_ros::ReadySrv&) { return value(); }
};


// service_traits::MD5Sum< ::svg_ros::ReadySrvRequest> should match 
// service_traits::MD5Sum< ::svg_ros::ReadySrv > 
template<>
struct MD5Sum< ::svg_ros::ReadySrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::svg_ros::ReadySrv >::value();
  }
  static const char* value(const ::svg_ros::ReadySrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::svg_ros::ReadySrvRequest> should match 
// service_traits::DataType< ::svg_ros::ReadySrv > 
template<>
struct DataType< ::svg_ros::ReadySrvRequest>
{
  static const char* value()
  {
    return DataType< ::svg_ros::ReadySrv >::value();
  }
  static const char* value(const ::svg_ros::ReadySrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::svg_ros::ReadySrvResponse> should match 
// service_traits::MD5Sum< ::svg_ros::ReadySrv > 
template<>
struct MD5Sum< ::svg_ros::ReadySrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::svg_ros::ReadySrv >::value();
  }
  static const char* value(const ::svg_ros::ReadySrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::svg_ros::ReadySrvResponse> should match 
// service_traits::DataType< ::svg_ros::ReadySrv > 
template<>
struct DataType< ::svg_ros::ReadySrvResponse>
{
  static const char* value()
  {
    return DataType< ::svg_ros::ReadySrv >::value();
  }
  static const char* value(const ::svg_ros::ReadySrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SVG_ROS_MESSAGE_READYSRV_H
