set(_CATKIN_CURRENT_PACKAGE "turtlebot_node")
set(turtlebot_node_VERSION "0.0.0")
set(turtlebot_node_MAINTAINER "edd <edd@todo.todo>")
set(turtlebot_node_PACKAGE_FORMAT "1")
set(turtlebot_node_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "message_generation")
set(turtlebot_node_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(turtlebot_node_BUILDTOOL_DEPENDS "catkin")
set(turtlebot_node_BUILDTOOL_EXPORT_DEPENDS )
set(turtlebot_node_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(turtlebot_node_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(turtlebot_node_TEST_DEPENDS )
set(turtlebot_node_DOC_DEPENDS )
set(turtlebot_node_DEPRECATED "")