// Generated by gencpp from file svg_ros/GetLaserServ.msg
// DO NOT EDIT!


#ifndef SVG_ROS_MESSAGE_GETLASERSERV_H
#define SVG_ROS_MESSAGE_GETLASERSERV_H

#include <ros/service_traits.h>


#include <svg_ros/GetLaserServRequest.h>
#include <svg_ros/GetLaserServResponse.h>


namespace svg_ros
{

struct GetLaserServ
{

typedef GetLaserServRequest Request;
typedef GetLaserServResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetLaserServ
} // namespace svg_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::svg_ros::GetLaserServ > {
  static const char* value()
  {
    return "51e72a4807785eaabb7cee7d2a968e03";
  }

  static const char* value(const ::svg_ros::GetLaserServ&) { return value(); }
};

template<>
struct DataType< ::svg_ros::GetLaserServ > {
  static const char* value()
  {
    return "svg_ros/GetLaserServ";
  }

  static const char* value(const ::svg_ros::GetLaserServ&) { return value(); }
};


// service_traits::MD5Sum< ::svg_ros::GetLaserServRequest> should match 
// service_traits::MD5Sum< ::svg_ros::GetLaserServ > 
template<>
struct MD5Sum< ::svg_ros::GetLaserServRequest>
{
  static const char* value()
  {
    return MD5Sum< ::svg_ros::GetLaserServ >::value();
  }
  static const char* value(const ::svg_ros::GetLaserServRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::svg_ros::GetLaserServRequest> should match 
// service_traits::DataType< ::svg_ros::GetLaserServ > 
template<>
struct DataType< ::svg_ros::GetLaserServRequest>
{
  static const char* value()
  {
    return DataType< ::svg_ros::GetLaserServ >::value();
  }
  static const char* value(const ::svg_ros::GetLaserServRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::svg_ros::GetLaserServResponse> should match 
// service_traits::MD5Sum< ::svg_ros::GetLaserServ > 
template<>
struct MD5Sum< ::svg_ros::GetLaserServResponse>
{
  static const char* value()
  {
    return MD5Sum< ::svg_ros::GetLaserServ >::value();
  }
  static const char* value(const ::svg_ros::GetLaserServResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::svg_ros::GetLaserServResponse> should match 
// service_traits::DataType< ::svg_ros::GetLaserServ > 
template<>
struct DataType< ::svg_ros::GetLaserServResponse>
{
  static const char* value()
  {
    return DataType< ::svg_ros::GetLaserServ >::value();
  }
  static const char* value(const ::svg_ros::GetLaserServResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SVG_ROS_MESSAGE_GETLASERSERV_H
