// Generated by gencpp from file svg_ros/LightSrv.msg
// DO NOT EDIT!


#ifndef SVG_ROS_MESSAGE_LIGHTSRV_H
#define SVG_ROS_MESSAGE_LIGHTSRV_H

#include <ros/service_traits.h>


#include <svg_ros/LightSrvRequest.h>
#include <svg_ros/LightSrvResponse.h>


namespace svg_ros
{

struct LightSrv
{

typedef LightSrvRequest Request;
typedef LightSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LightSrv
} // namespace svg_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::svg_ros::LightSrv > {
  static const char* value()
  {
    return "eba6c43e856487b2b6ad559a0d0f124d";
  }

  static const char* value(const ::svg_ros::LightSrv&) { return value(); }
};

template<>
struct DataType< ::svg_ros::LightSrv > {
  static const char* value()
  {
    return "svg_ros/LightSrv";
  }

  static const char* value(const ::svg_ros::LightSrv&) { return value(); }
};


// service_traits::MD5Sum< ::svg_ros::LightSrvRequest> should match 
// service_traits::MD5Sum< ::svg_ros::LightSrv > 
template<>
struct MD5Sum< ::svg_ros::LightSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::svg_ros::LightSrv >::value();
  }
  static const char* value(const ::svg_ros::LightSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::svg_ros::LightSrvRequest> should match 
// service_traits::DataType< ::svg_ros::LightSrv > 
template<>
struct DataType< ::svg_ros::LightSrvRequest>
{
  static const char* value()
  {
    return DataType< ::svg_ros::LightSrv >::value();
  }
  static const char* value(const ::svg_ros::LightSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::svg_ros::LightSrvResponse> should match 
// service_traits::MD5Sum< ::svg_ros::LightSrv > 
template<>
struct MD5Sum< ::svg_ros::LightSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::svg_ros::LightSrv >::value();
  }
  static const char* value(const ::svg_ros::LightSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::svg_ros::LightSrvResponse> should match 
// service_traits::DataType< ::svg_ros::LightSrv > 
template<>
struct DataType< ::svg_ros::LightSrvResponse>
{
  static const char* value()
  {
    return DataType< ::svg_ros::LightSrv >::value();
  }
  static const char* value(const ::svg_ros::LightSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SVG_ROS_MESSAGE_LIGHTSRV_H
