// Generated by gencpp from file svg_ros/MVPlannerSrv.msg
// DO NOT EDIT!


#ifndef SVG_ROS_MESSAGE_MVPLANNERSRV_H
#define SVG_ROS_MESSAGE_MVPLANNERSRV_H

#include <ros/service_traits.h>


#include <svg_ros/MVPlannerSrvRequest.h>
#include <svg_ros/MVPlannerSrvResponse.h>


namespace svg_ros
{

struct MVPlannerSrv
{

typedef MVPlannerSrvRequest Request;
typedef MVPlannerSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MVPlannerSrv
} // namespace svg_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::svg_ros::MVPlannerSrv > {
  static const char* value()
  {
    return "5f074d799916e31d387cc1b1bc10d8d7";
  }

  static const char* value(const ::svg_ros::MVPlannerSrv&) { return value(); }
};

template<>
struct DataType< ::svg_ros::MVPlannerSrv > {
  static const char* value()
  {
    return "svg_ros/MVPlannerSrv";
  }

  static const char* value(const ::svg_ros::MVPlannerSrv&) { return value(); }
};


// service_traits::MD5Sum< ::svg_ros::MVPlannerSrvRequest> should match 
// service_traits::MD5Sum< ::svg_ros::MVPlannerSrv > 
template<>
struct MD5Sum< ::svg_ros::MVPlannerSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::svg_ros::MVPlannerSrv >::value();
  }
  static const char* value(const ::svg_ros::MVPlannerSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::svg_ros::MVPlannerSrvRequest> should match 
// service_traits::DataType< ::svg_ros::MVPlannerSrv > 
template<>
struct DataType< ::svg_ros::MVPlannerSrvRequest>
{
  static const char* value()
  {
    return DataType< ::svg_ros::MVPlannerSrv >::value();
  }
  static const char* value(const ::svg_ros::MVPlannerSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::svg_ros::MVPlannerSrvResponse> should match 
// service_traits::MD5Sum< ::svg_ros::MVPlannerSrv > 
template<>
struct MD5Sum< ::svg_ros::MVPlannerSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::svg_ros::MVPlannerSrv >::value();
  }
  static const char* value(const ::svg_ros::MVPlannerSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::svg_ros::MVPlannerSrvResponse> should match 
// service_traits::DataType< ::svg_ros::MVPlannerSrv > 
template<>
struct DataType< ::svg_ros::MVPlannerSrvResponse>
{
  static const char* value()
  {
    return DataType< ::svg_ros::MVPlannerSrv >::value();
  }
  static const char* value(const ::svg_ros::MVPlannerSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SVG_ROS_MESSAGE_MVPLANNERSRV_H
