// Generated by gencpp from file svg_ros/SensorSrv.msg
// DO NOT EDIT!


#ifndef SVG_ROS_MESSAGE_SENSORSRV_H
#define SVG_ROS_MESSAGE_SENSORSRV_H

#include <ros/service_traits.h>


#include <svg_ros/SensorSrvRequest.h>
#include <svg_ros/SensorSrvResponse.h>


namespace svg_ros
{

struct SensorSrv
{

typedef SensorSrvRequest Request;
typedef SensorSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SensorSrv
} // namespace svg_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::svg_ros::SensorSrv > {
  static const char* value()
  {
    return "b3a08c1472f241ab9eb4c0932b73ff18";
  }

  static const char* value(const ::svg_ros::SensorSrv&) { return value(); }
};

template<>
struct DataType< ::svg_ros::SensorSrv > {
  static const char* value()
  {
    return "svg_ros/SensorSrv";
  }

  static const char* value(const ::svg_ros::SensorSrv&) { return value(); }
};


// service_traits::MD5Sum< ::svg_ros::SensorSrvRequest> should match 
// service_traits::MD5Sum< ::svg_ros::SensorSrv > 
template<>
struct MD5Sum< ::svg_ros::SensorSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::svg_ros::SensorSrv >::value();
  }
  static const char* value(const ::svg_ros::SensorSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::svg_ros::SensorSrvRequest> should match 
// service_traits::DataType< ::svg_ros::SensorSrv > 
template<>
struct DataType< ::svg_ros::SensorSrvRequest>
{
  static const char* value()
  {
    return DataType< ::svg_ros::SensorSrv >::value();
  }
  static const char* value(const ::svg_ros::SensorSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::svg_ros::SensorSrvResponse> should match 
// service_traits::MD5Sum< ::svg_ros::SensorSrv > 
template<>
struct MD5Sum< ::svg_ros::SensorSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::svg_ros::SensorSrv >::value();
  }
  static const char* value(const ::svg_ros::SensorSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::svg_ros::SensorSrvResponse> should match 
// service_traits::DataType< ::svg_ros::SensorSrv > 
template<>
struct DataType< ::svg_ros::SensorSrvResponse>
{
  static const char* value()
  {
    return DataType< ::svg_ros::SensorSrv >::value();
  }
  static const char* value(const ::svg_ros::SensorSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SVG_ROS_MESSAGE_SENSORSRV_H
