// Generated by gencpp from file svg_ros/InputsPlannerSrv.msg
// DO NOT EDIT!


#ifndef SVG_ROS_MESSAGE_INPUTSPLANNERSRV_H
#define SVG_ROS_MESSAGE_INPUTSPLANNERSRV_H

#include <ros/service_traits.h>


#include <svg_ros/InputsPlannerSrvRequest.h>
#include <svg_ros/InputsPlannerSrvResponse.h>


namespace svg_ros
{

struct InputsPlannerSrv
{

typedef InputsPlannerSrvRequest Request;
typedef InputsPlannerSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct InputsPlannerSrv
} // namespace svg_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::svg_ros::InputsPlannerSrv > {
  static const char* value()
  {
    return "188578d1209fb9d01aa3d1efc9744987";
  }

  static const char* value(const ::svg_ros::InputsPlannerSrv&) { return value(); }
};

template<>
struct DataType< ::svg_ros::InputsPlannerSrv > {
  static const char* value()
  {
    return "svg_ros/InputsPlannerSrv";
  }

  static const char* value(const ::svg_ros::InputsPlannerSrv&) { return value(); }
};


// service_traits::MD5Sum< ::svg_ros::InputsPlannerSrvRequest> should match 
// service_traits::MD5Sum< ::svg_ros::InputsPlannerSrv > 
template<>
struct MD5Sum< ::svg_ros::InputsPlannerSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::svg_ros::InputsPlannerSrv >::value();
  }
  static const char* value(const ::svg_ros::InputsPlannerSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::svg_ros::InputsPlannerSrvRequest> should match 
// service_traits::DataType< ::svg_ros::InputsPlannerSrv > 
template<>
struct DataType< ::svg_ros::InputsPlannerSrvRequest>
{
  static const char* value()
  {
    return DataType< ::svg_ros::InputsPlannerSrv >::value();
  }
  static const char* value(const ::svg_ros::InputsPlannerSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::svg_ros::InputsPlannerSrvResponse> should match 
// service_traits::MD5Sum< ::svg_ros::InputsPlannerSrv > 
template<>
struct MD5Sum< ::svg_ros::InputsPlannerSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::svg_ros::InputsPlannerSrv >::value();
  }
  static const char* value(const ::svg_ros::InputsPlannerSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::svg_ros::InputsPlannerSrvResponse> should match 
// service_traits::DataType< ::svg_ros::InputsPlannerSrv > 
template<>
struct DataType< ::svg_ros::InputsPlannerSrvResponse>
{
  static const char* value()
  {
    return DataType< ::svg_ros::InputsPlannerSrv >::value();
  }
  static const char* value(const ::svg_ros::InputsPlannerSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SVG_ROS_MESSAGE_INPUTSPLANNERSRV_H
